In [1]:
import requests
import pandas as pd
import numpy as np
import pickle
import json
from tqdm import tqdm

from util_scrape import get_player_data, get_todays_data, save_obj, load_obj

restart_database = False 
check_response   = False

In [2]:
# load previously scraped player data
p_names = pd.read_csv('00_global_player_database/player_list_v2.csv').col.tolist()
len(p_names)

4203

In [3]:
# respnese check to make sure api call exists for each player - look at the rejects and figure out why
listy = []
if check_response == True:
    for i in p_names:
        url = 'https://api-prod.footballindex.co.uk/v2/timeseries?id='+i+'&period=30d&interval=1d'
        response = requests.get(url)
        if str(response) == '<Response [404]>':
            print(i)
            listy.append(i)

In [6]:
# get player data!
player_dict = {}

if restart_database == True:
    for nam in p_names:
        name, data = get_player_data(nam)
        # append to player dictionary
        player_dict.update({name:data})

    # save off global player database
    save_obj(player_dict, 'FI_global_player_price_data_full_prem_v0')
    load_obj('FI_global_player_price_data_full_prem_v0')

In [7]:
# load player database 
player_database = load_obj('FI_global_player_price_data_full_prem_v5')

# load refreshed player data
player_dict_update = {}
for nam in tqdm(p_names):
    name, data = get_player_data(nam)
    
    if name in player_database:
          # merge with player database
        data = pd.concat((player_database[name], data[data.DateTime >= player_database[name]['DateTime'].max()]), axis=0)
        data.drop_duplicates(subset='DateTime',inplace=True, keep='last')
        data.sort_values('DateTime', inplace=True)
    else:
        data.sort_values('DateTime', inplace=True)
    
    # merge with data for today
    name_check, data_today = get_todays_data(name)
    # merge with data for today
    data = pd.concat((data, data_today), axis=0)
    data.drop_duplicates(subset='DateTime', inplace=True, keep='last')
    data.sort_values('DateTime', inplace=True)
    data.reset_index(inplace=True, drop=True)
  
    # append to player dictionary
    player_dict_update.update({name:data})
    
# save off new player database    
save_obj(player_dict_update, 'FI_global_player_price_data_full_prem_v5')

100%|██████████| 4203/4203 [40:31<00:00,  1.94it/s]

In [8]:
player_dict_update['paul-pogba']

     DateTime  Volume  maxPrice  minPrice  avgPrice
0  2019-07-09  4488.0      6.99      6.82      6.90
1  2019-07-10  3162.0      7.06      6.99      7.02
2  2019-07-11  2165.0      7.06      7.04      7.05
3  2019-07-12  1884.0      7.11      7.05      7.08
4  2019-07-13  1729.0      7.12      7.10      7.12
..        ...     ...       ...       ...       ...
75 2019-09-22  2090.0      6.36      6.25      6.31
76 2019-09-23  2078.0      6.39      6.26      6.33
77 2019-09-24  5405.0      6.57      6.39      6.52
78 2019-09-25  2566.0      6.65      6.54      6.62
79 2019-09-26    89.2      6.65      6.64      6.64

[80 rows x 5 columns]